### ISSUE TITLE
Showing Option For Viewing And Downloading Without Refreshing

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#15]
Currenly we are refreshing the page for giving the preview and download button to the user. These options should be provided without refreshing the page.

**Comment by pdcode1** [comment]
I'll check this

**Comment by samarth777** [comment]
if this isn't solved yet can you assign it to me?

**Comment by kailashchoudhary11** [comment]
> if this isn't solved yet can you assign it to me?

@samarth777 Someone is already working on this issue. Are you good at frontend?

**Comment by samarth777** [comment]
Yes I am good at frontend

**Comment by kailashchoudhary11** [comment]
@samarth777 let's discuss on discord kai_11#4616

**Comment by samarth777** [comment]
Sure okay
