### ISSUE TITLE
Update Table of Contents In Readme File

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#24]

**Comment by ArchitKumar-13** [comment]
Is this still open or is the contribution already made?

**Comment by kailashchoudhary11** [comment]
> Is this still open or is the contribution already made?

It is Still Open. Would you like to fix it?

**Comment by pratyusha0710** [comment]
@kailashchoudhary11 can you assign the issue to me?

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 can you assign the issue to me?

@pratyusha0710 Sure! You can make a PR!

**Comment by samarth777** [comment]
Can you assign this to me?

**Comment by kailashchoudhary11** [comment]
> Can you assign this to me?

I've already assigned it! You can raise some new issue if you want

**Comment by 0xtdey** [comment]
Is the issue still open? Would like to contribute
