### ISSUE TITLE
Creating Contact Us Page

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#25]

**Comment by musavveer** [comment]
Assign this issue to me. I can work on it

**Comment by kailashchoudhary11** [comment]
Go Ahead!

**Comment by Aditi-1709** [comment]
Is there any issue open so I can work in it ?

**Comment by kailashchoudhary11** [comment]
Hey @Aditi-1709 I have opened one new issue! Comment on it I'll assign it to you!

**Comment by kailashchoudhary11** [comment]
@musavveer Are you working on it?

**Comment by musavveer** [comment]
> @musavveer Are you working on it?

Yeah

**Comment by kailashchoudhary11** [comment]
> > @musavveer Are you working on it?
> 
> Yeah

okk

**Comment by musavveer** [comment]
I am unable to setup database. It is throwing me an error.>>

**Comment by kailashchoudhary11** [comment]
> I am unable to setup database. It is throwing me an error.>>

which error did you follow all the steps from contributing.md

**Comment by musavveer** [comment]
> > I am unable to setup database. It is throwing me an error.>>
> 
> which error did you follow all the steps from contributing.md
<img width="1680" alt="Screenshot 2022-10-20 at 3 39 35 PM" src="https://user-images.githubusercontent.com/62888562/196921399-120d97b1-9fbb-4f98-9853-d55f82e2f3b4.png">


Yeah I followed all the steps.
I have attached a screenshot of the error.

**Comment by kailashchoudhary11** [comment]
@musavveer 
Create a new .env file same as the .env.example file. I have updated the steps in contributing.md

**Comment by musavveer** [comment]
It worked. Thank you

**Comment by musavveer** [comment]
@kailashchoudhary11 Shall i create a new file for contact-us page in templates

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 Shall i create a new file for contact-us page in templates

yeah create it in templates directory

**Comment by kailashchoudhary11** [comment]
@musavveer Any updates?

**Comment by musavveer** [comment]
I am working on it..

**Comment by kailashchoudhary11** [comment]
> I am working on it..

Bro it has been 5 days! This is not that difficult task i suposse

**Comment by musavveer** [comment]
@kailashchoudhary11 How should I give the path here `<li>
        <a class="active" href="templates/contact.html"><i class="glyphicon glyphicon-user"></i>Contact us</a>
      </li>`

**Comment by kailashchoudhary11** [comment]
`<li> <a class="active" href="contact.html"><i class="glyphicon glyphicon-user"></i>Contact us</a> </li>`

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 How should I give the path here `<li> <a class="active" href="templates/contact.html"><i class="glyphicon glyphicon-user"></i>Contact us</a> </li>`

that is bit complicated i will handle it you can just create a pr after creating contact.html
