### ISSUE TITLE
Design a Logo for the website!

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#30]

**Comment by 0xtdey** [comment]
kindly assign me this issue

**Comment by 0xtdey** [comment]
![Instagram post - 58](https://user-images.githubusercontent.com/91402167/196758714-faa69b1a-6e53-4068-9f93-2c4ea649833e.png)
I tried making this, really simple logo hope you like it.

**Comment by kailashchoudhary11** [comment]
@tamoghna-dey Please include whole name in the logo **imgman**

**Comment by 0xtdey** [comment]
Yes sure, here's another variation
![Instagram post - 59](https://user-images.githubusercontent.com/91402167/196858178-a1bf97e4-8372-4298-b976-a258add3fcb0.png)
