### ISSUE TITLE
Add Project Description in Readme File

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#4]
Complete the Readme file by adding Table of Contents, Various Sections and Necessary Links!

**Comment by highb33kay** [comment]
Assign me @kailashchoudhary11. I'd also like to contribute with code. If there is anything you have that is beginner friendly.

**Comment by kailashchoudhary11** [comment]
Go Ahead! In which part would you like to contribute through code? Frontend or Backend?

**Comment by highb33kay** [comment]
I was thinking backend because I would like to build more collaboration
experience with python and django

**Comment by kailashchoudhary11** [comment]
Oh Great! Maybe we can connect on Discord?

**Comment by highb33kay** [comment]
Sure, that works for me.

**Comment by kailashchoudhary11** [comment]
@highb33kay ``kai_11#4616`` This is my discord id

**Comment by highb33kay** [comment]
Done and attached a pr #10
