### ISSUE TITLE
Customizing the Home Page!

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#42]
Add the upload image section in the home page and also some details about the project!

**Comment by CodeRyliCode** [comment]
Hi I would like to work on this.

**Comment by dasashreeya** [comment]
Hello, I would like to contribute

**Comment by kailashchoudhary11** [comment]
> Hi I would like to work on this.

@CodeRyliCode Okay Go Ahead I'll assign it to you!

**Comment by kailashchoudhary11** [comment]
> Hello, I would like to contribute

Take a look at this issue https://github.com/kailashchoudhary11/imgman/issues/41 If you want I can assign it to you! @dasashreeya

**Comment by shrishti147** [comment]
hi, i would like to work on this

**Comment by kailashchoudhary11** [comment]
> hi, i would like to work on this

@shrishti147  I have already assigned this issue to someone. Take a look at other issues!

**Comment by dasashreeya** [comment]
Hello,
Yes, I'm working on issue #41.
(Creating the footer)

**Comment by dasashreeya** [comment]
> > Hello, I would like to contribute
> 
> Take a look at this issue #41 If you want I can assign it to you! @dasashreeya

Yes, can you please assign issue #41 to me?

**Comment by CodeRyliCode** [comment]
@kailashchoudhary11 Thank you!!

**Comment by kailashchoudhary11** [comment]
> > > Hello, I would like to contribute
> > 
> > 
> > Take a look at this issue #41 If you want I can assign it to you! @dasashreeya
> 
> Yes, can you please assign issue #41 to me?

@dasashreeya Yeah I have assigned that one to you, you can start working!

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 Thank you!!

Any Updates?

**Comment by deepaksuthar40128** [comment]
can you assign it to me

**Comment by tejus0** [comment]
Hey @kailashchoudhary11 is this issue still open to work on? Can you assign it to me?

**Comment by kailashchoudhary11** [comment]
@CodeRyliCode You are working on it right?

**Comment by CodeRyliCode** [comment]
Hi if there’s a time constraint on this, you can just assign it to someone
else . Sorry, I was trying to do it but I can’t finish it in time and I
don’t know python that well.

**Comment by kailashchoudhary11** [comment]
@CodeRyliCode You can take your time. Let me know if you need any help.

**Comment by CodeRyliCode** [comment]
Actually you can assign it to someone else because I won’t have the bandwidth. Thank you!!

**Comment by musavveer** [comment]
Is anyone working on the issue? If not please assign it to me.

**Comment by kailashchoudhary11** [comment]
@musavveer Yeah you can work on it! Go Ahead!
