### ISSUE TITLE
Creating Functions for Steganography

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#44]
Create Two Functions: 
One for hiding text in the image. 
The other one for extracting text from the image.

**Comment by Swap-Nova** [comment]
Hey, I would like to work on this. Can you assign it to me?

**Comment by kailashchoudhary11** [comment]
> Hey, I would like to work on this. Can you assign it to me?

Sure go Ahead!

**Comment by Swap-Nova** [comment]
Thanks

**Comment by kailashchoudhary11** [comment]
> Thanks

Join Our Discord Server if you need any help https://discord.gg/GWvNKAKkJS

**Comment by Swap-Nova** [comment]
Sent you the PR. Do look into it.

**Comment by Swap-Nova** [comment]
@kailashchoudhary11 Does the code work for you? If yes, please merge it.

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 Does the code work for you? If yes, please merge it.

But the code is unnecessary 🥲

**Comment by Swap-Nova** [comment]
@kailashchoudhary11 Okay, no problem. Give me till EOD, by that time I will update the PR ;)

**Comment by Swap-Nova** [comment]
@kailashchoudhary11 also can you tell me what exactly do you need?
Not the code it seems, so documentation of the procedure to hide the text?

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 also can you tell me what exactly do you need? Not the code it seems, so documentation of the procedure to hide the text?

I can assign you some other issue if you want. I will handle this one

**Comment by Swap-Nova** [comment]
If it's fine, I can work on it I believe. 
But if you want to assign me different issue I can work on 'About Us' Page.

**Comment by Swap-Nova** [comment]
But @kailashchoudhary11 can you like explain me what do you need me to do in this issue... Like provide code or documentation or something else?
Bit confused here bud xd

**Comment by kailashchoudhary11** [comment]
> But @kailashchoudhary11 can you like explain me what do you need me to do in this issue... Like provide code or documentation or something else? Bit confused here bud xd

Actually I have already implemented the functions for this it was quite simple you can take a look at steg/functions.py

**Comment by kailashchoudhary11** [comment]
> If it's fine, I can work on it I believe. But if you want to assign me different issue I can work on 'About Us' Page.

@Swap-Nova  You can work on the Home Page and add informaition about Steganography in the home page is it okay?

**Comment by Swap-Nova** [comment]
@kailashchoudhary11 Can I write about the steganography as an Readme.md documentation and work on the code side-by-side?

**Comment by kailashchoudhary11** [comment]
@Swap-Nova Okay sure. Don't add much text in readme. you can add more text in the home page

**Comment by Swap-Nova** [comment]
Great will work on it.

**Comment by Swap-Nova** [comment]
@kailashchoudhary11 Added some info on the home page & a folder of Steganography Code with it's Readme.md file
