### ISSUE TITLE
Create Template for Issues

### ISSUE THREAD

**Issue by kailashchoudhary11** [kailashchoudhary11/imgman#49]
Create template for Bug Report, New Feature Request, Improvement to Existing Functionality

**Comment by israelmitolu** [comment]
Hi @kailashchoudhary11 
Kindly assign this issue to me

**Comment by kailashchoudhary11** [comment]
> Hi @kailashchoudhary11 Kindly assign this issue to me

Go Ahead but please don't copy the templates from somewhere and don't include unnecessary text!

**Comment by israelmitolu** [comment]
Noted. Thank you

**Comment by shrishti147** [comment]
please assign me.

**Comment by kailashchoudhary11** [comment]
> please assign me.

@shrishti147 I have already assigned it to someone! Would you like to contribute to frontend mostly CSS???

**Comment by Ghat0tkach** [comment]
@kailashchoudhary11 i would love to contribute to the frontend part

**Comment by kailashchoudhary11** [comment]
> @kailashchoudhary11 i would love to contribute to the frontend part

Dm on discord!!
