### ISSUE TITLE
Screenshots not visible in readme file

### ISSUE THREAD

**Issue by MartinaVukanovic** [kailashchoudhary11/imgman#56]
There is an issue with screenshots at readme file as they are shown as markdown language not an image.

![Screenshot 2022-10-23 013706](https://user-images.githubusercontent.com/49649259/197366248-a4a889a5-12a9-47d8-b8e2-3a21ab820eff.png)

If correct location for wanted images exists, or you do not need this section anymore I can update or delete it from readme file.

**Comment by MartinaVukanovic** [comment]
If there is a correct location for wanted images, or you do not need this section anymore I can update or delete it from readme file.

**Comment by kailashchoudhary11** [comment]
You can go and check our website over here imgman.herokuapp.com Upload some image, manipulate it and paste the original image along with manipulated images

**Comment by Tejas124** [comment]
Hi, I'm Tejas. I would like to add few screenshots of the website. Below are the some screenshots I have taken.
If it's useful then I will create a PR.

<img width="960" alt="Screenshot_20221023_080950" src="https://user-images.githubusercontent.com/79836871/197370657-12eb4f4c-97ea-4ae8-9009-b259e5a3dbd5.png">

<img width="960" alt="Screenshot_20221023_081022" src="https://user-images.githubusercontent.com/79836871/197370663-71a12aed-ba6d-4389-a320-6cb5095d197f.png">

**Comment by kailashchoudhary11** [comment]
@Tejas124  Someone is already working on this issue! You may raise some other issues

**Comment by Tejas124** [comment]
@kailashchoudhary11  Okay 👍🏻
