### ISSUE TITLE
Providing Description in Steganography Section By ading some text or Images

### ISSUE THREAD

**Issue by yashphalle** [kailashchoudhary11/imgman#78]
## Is your improvement related to a problem? Please describe.
When a new user will come across our website then there is might possible that he does not know the meaning of Steganography.

## Describe the improvement you'd like
So I think we can describe this feature in short by adding what is Steganography. in the red box that I have attached in screenshot below or the empty area on sides.
![image](https://user-images.githubusercontent.com/82230267/198104074-54b20745-2241-47f0-ae7e-aee00b8cb2ff.png)

## Why should this improvement be made?
It will be really helpful for users to understand and it will make more users to use this feature.

## Additional context
We can add some Images to make it more interactive.
![download (1)](https://user-images.githubusercontent.com/82230267/198104524-04b154b6-023f-4d83-af94-66425df7c449.jpg)
![download](https://user-images.githubusercontent.com/82230267/198104531-bdc94162-7a57-427c-9bf7-a155d689f5a3.jpg)

## Has this improvement been discussed before?
No

## Does the feature change existing behavior?

No

**Comment by kailashchoudhary11** [comment]
@yashphalle Go Ahead!! Add this on the Home Page!

**Comment by kailashchoudhary11** [comment]
@yashphalle Also Do join our discord server!

**Comment by kailashchoudhary11** [comment]
****

**Comment by yashphalle** [comment]
Hey, Can we reopen this issue?
