### ISSUE TITLE
Add Descriptive Homepage

### ISSUE THREAD

**Issue by ashmitjsg** [kailashchoudhary11/imgman#80]
## Add a description of Imgman on the homepage

There is only "Hello World" written on the homepage. We can add a description of ImgMan on the homepage so that new users can know about what the website does.

## Describe the solution you'd like

We should add the functionality of Imgman on the homepage.

## Additional context
Currently, the homepage looks like this.
![image](https://user-images.githubusercontent.com/43639341/198198898-d30ed9fa-9fee-4845-8c0e-e2933641ac61.png)

**Comment by kailashchoudhary11** [comment]
Would you like to work on this?

**Comment by ashmitjsg** [comment]
Sure I can try!

**Comment by kailashchoudhary11** [comment]
@devilkiller-ag Go Ahead

**Comment by ashmitjsg** [comment]
Thank you @kailashchoudhary11

**Comment by IM-TECHNO** [comment]
Can i also work on this ? i'm doing this for hacktoberfest.

**Comment by ashmitjsg** [comment]
@kailashchoudhary11 please assign this issue to @ as I will not be able to work on this issue further. Sorry for the Inconviniences.
