### ISSUE TITLE
About page contains a different language other than english , and might be a trouble for english talking people.

### ISSUE THREAD

**Issue by S-HARI-S** [kailashchoudhary11/imgman#92]
## Why should this improvement be made?

A concise description of why this improvement should be made.

## Has this improvement been discussed before?

Please provide a link to the issue.

## Does the feature change existing behavior?

If so, why is the change needed?

**Comment by kailashchoudhary11** [comment]
@S-HARI-S you can work on the ui design on the about us page. The figma link is in the Contributing.md file. Also you can join discord server if you need any help!
